### ISSUE TITLE
_checkForSaveDirectory in dnatracing.py path joins cause problems on Windows

### ISSUE THREAD

**Issue by derollins** [afmstats/TopoStats#11]
Path joins are being done as string manipulations rather than `os.path.join`. This causes issues in windows when input path includes `\` or if the input files are nested in a folder within the path file. 

Will try and solve by using `os.path.join`

**Comment by bobturneruk** [comment]
Has this been resolved by #12? If so, please close this issue @derollins.

**Comment by derollins** [comment]
I think it has so will close.
